"""fix refresh token table

Revision ID: 103447b742e7
Revises: 8752f00e3b9f
Create Date: 2026-01-27 10:40:54.163897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '103447b742e7'
down_revision: Union[str, None] = '8752f00e3b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('refreshtoken', 'exprires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('exprires_at', mysql.DATETIME(), nullable=False))
    op.drop_column('refreshtoken', 'expires_at')
    # ### end Alembic commands ###
