"""add like_count to Post

Revision ID: 680d59182551
Revises: b069cfc6027e
Create Date: 2025-03-29 13:59:09.857685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '680d59182551'
down_revision: Union[str, None] = 'b069cfc6027e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like_count')
    # ### end Alembic commands ###
