"""change post table

Revision ID: b069cfc6027e
Revises: 1be53091bf91
Create Date: 2025-03-25 23:18:40.057314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b069cfc6027e'
down_revision: Union[str, None] = '1be53091bf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('post', 'titile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('titile', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
